# Generated by Django 3.0.2 on 2020-01-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KayitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcKimlikNo', models.BigIntegerField()),
                ('adi', models.CharField(max_length=200)),
                ('soyadi', models.CharField(max_length=200)),
                ('cinsiyet', models.CharField(choices=[('1', 'Erkek'), ('2', 'Kız')], max_length=20)),
            ],
        ),
    ]
