# Generated by Django 3.0.2 on 2020-01-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kayit', '0002_auto_20200105_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kayitmodel',
            name='eposta',
            field=models.EmailField(default='aa@a.com', max_length=254, unique=True),
        ),
    ]
